### ISSUE TITLE
Kræsj når man trykker på tidligere obs. pins på tidligere turer

### ISSUE THREAD

**Issue by mchyll** [mchyll/sausee#120]
Og i tillegg: Tidligere, før det begynte å kræsje, kunne man trykke seg inn i FS for tidligere obs. og så inn i CS, men der stod det bare 0 og man kunne ikke telle. Fordi den leter etter observasjonen som settes i currentTrip, men klarte ikke å finne den der.

**Comment by Trulsmatias** [comment]
Går ikke lenger ann å trykke på observasjoner fra tidligere turer. #e3bf9cd7a795d6c697abe5309d3dac2409fb9e4a
