### ISSUE TITLE
Make it pretty

### ISSUE THREAD

**Issue by Trulsmatias** [mchyll/sausee#17]

**Comment by mchyll** [comment]
Sette `style: "cancel"` på avbryt-knapper

_Originally posted by @mchyll in https://github.com/mchyll/sausee/pull/52#discussion_r506193419_

**Comment by Trulsmatias** [comment]
download map knappen
sette posisjon til sauer knappene
Gjøre det tydelig at man er på forskjellige skjermene
avslutte trip knapp
formen generelt
fullfør/avbryt knappene i formen
elementene swipecounteren
feilmeldinger

Runde knapper/firkantet?
fargepallet

**Comment by Trulsmatias** [comment]
For feilmeldinger https://medium.com/thinking-design/how-to-write-design-user-friendly-error-messages-87d0207bb902
