### ISSUE TITLE
Phrasing

### ISSUE THREAD

**Issue by mchyll** [mchyll/sausee#59]
Bør nok omformulere disse etterhvert. Dette kan høres ut som at vi _vet_ at brukeren har sett og registrert feil farge på dyrene & slipsene, men handler egentlig om at det er en uoverensstemmelse og potensielt mangler lam pga. rovdyr eller at brukeren har oversett et slips eller et dyr

_Originally posted by @mchyll in https://github.com/mchyll/sausee/pull/55#discussion_r506304208_

**Comment by Trulsmatias** [comment]
Closer fordi det ikke er fikset og relevant lengre.
