### ISSUE TITLE
Endre ordbruk i "Totalt antall" og "Nær/fjernregistrering"

### ISSUE THREAD

**Issue by mchyll** [mchyll/sausee#80]
> **Forventninger om at totalantall summeres automatisk.**
> Flere brukere uttrykte at de trodde feltet for totalt antall sauer skulle summeres automatisk basert på det som ble registrert i de forskjellige sauekategoriene. En bruker kommenterte at hen kunne utelate å registrere totalantall, og dermed få en observasjon med uoverensstemmelse mellom totalen og antallet av hver sauetype.

> **Uklart hvorfor en kan bytte mellom nær- og fjernregistrering.**
> En bruker ga tilbakemelding om at hen ikke la merke til knappen for å bytte mellom nær- og fjernregistrering med det første. Det ble også uttrykt at poenget med forskjellige skjema for nær- og fjernregistrering ikke var forståelig, siden det kun endret om slips skulle registreres eller ikke.

**Comment by Trulsmatias** [comment]
Vil ikke oppdatere seg av en eller annen grunn. Vil parprogge det.
