### ISSUE TITLE
Bytte ut snipersiktet med pin/dråpe, kanskje fjerne siktlinje

### ISSUE THREAD

**Issue by mchyll** [mchyll/sausee#81]
> **Delte erfaringer rundt snipersiktet i kart for registrering av observasjoner**
> Det var ikke alltid tydelig at snipersiktet i kart for registrering av observasjoner skulle brukes til å sette posisjonene til sauene man hadde observert. Noen brukere antok at det skulle brukes til å sette egen posisjon. Det ble også brukt av en bruker for sikte på den observasjonen som skulle redigeres, selv om dette kan gjøres ved å trykke på sauen som representerer observasjonen, uten å bruke snipersiktet først. De gangene brukeren forstår at snipersiktet skal brukes til å registere saueposisjonen er det fordi hen leser tittelen på siden, ikke fordi snipersiktet er intuitivt i seg selv. Noen brukere tror siktet er trykkbart og at man skal trykke på det for å registere en posisjon.
> Ingen brukere skjønner hva siktlinjen betyr, eller velger å ignorere den. En bruker resonerer seg fram til at det betyr retningen man ser.

**Comment by Trulsmatias** [comment]
samme pin/dråpe som i #86
